//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/andre/Documents/GitHub/nancy-expressions/Nancy.Expressions/Nancy.Expressions/Grammar/NetCalG.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


#pragma warning disable 3021

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="NetCalGParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface INetCalGVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="NetCalGParser.equivalenceCatalog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquivalenceCatalog([NotNull] NetCalGParser.EquivalenceCatalogContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NetCalGParser.equivalence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquivalence([NotNull] NetCalGParser.EquivalenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NetCalGParser.equivalenceExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquivalenceExpression([NotNull] NetCalGParser.EquivalenceExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NetCalGParser.hypothesis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHypothesis([NotNull] NetCalGParser.HypothesisContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NetCalGParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet([NotNull] NetCalGParser.SetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NetCalGParser.placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlaceholder([NotNull] NetCalGParser.PlaceholderContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nonDecreasingProperty</c>
	/// labeled alternative in <see cref="NetCalGParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonDecreasingProperty([NotNull] NetCalGParser.NonDecreasingPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nonNegativeProperty</c>
	/// labeled alternative in <see cref="NetCalGParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonNegativeProperty([NotNull] NetCalGParser.NonNegativePropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>subadditiveProperty</c>
	/// labeled alternative in <see cref="NetCalGParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubadditiveProperty([NotNull] NetCalGParser.SubadditivePropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>convexProperty</c>
	/// labeled alternative in <see cref="NetCalGParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConvexProperty([NotNull] NetCalGParser.ConvexPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>concaveProperty</c>
	/// labeled alternative in <see cref="NetCalGParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcaveProperty([NotNull] NetCalGParser.ConcavePropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>leftContinuousProperty</c>
	/// labeled alternative in <see cref="NetCalGParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeftContinuousProperty([NotNull] NetCalGParser.LeftContinuousPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>rightContinuousProperty</c>
	/// labeled alternative in <see cref="NetCalGParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRightContinuousProperty([NotNull] NetCalGParser.RightContinuousPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>zeroAtZeroProperty</c>
	/// labeled alternative in <see cref="NetCalGParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitZeroAtZeroProperty([NotNull] NetCalGParser.ZeroAtZeroPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ultimatelyConstant</c>
	/// labeled alternative in <see cref="NetCalGParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUltimatelyConstant([NotNull] NetCalGParser.UltimatelyConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>compositionExpression</c>
	/// labeled alternative in <see cref="NetCalGParser.curveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompositionExpression([NotNull] NetCalGParser.CompositionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenthesizedExpression</c>
	/// labeled alternative in <see cref="NetCalGParser.curveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesizedExpression([NotNull] NetCalGParser.ParenthesizedExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>maxPlusDeconvolutionExpression</c>
	/// labeled alternative in <see cref="NetCalGParser.curveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaxPlusDeconvolutionExpression([NotNull] NetCalGParser.MaxPlusDeconvolutionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>additionExpression</c>
	/// labeled alternative in <see cref="NetCalGParser.curveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditionExpression([NotNull] NetCalGParser.AdditionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>convolutionExpression</c>
	/// labeled alternative in <see cref="NetCalGParser.curveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConvolutionExpression([NotNull] NetCalGParser.ConvolutionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>constantCurveExpression</c>
	/// labeled alternative in <see cref="NetCalGParser.curveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantCurveExpression([NotNull] NetCalGParser.ConstantCurveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>deconvolutionExpression</c>
	/// labeled alternative in <see cref="NetCalGParser.curveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeconvolutionExpression([NotNull] NetCalGParser.DeconvolutionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>subtractionExpression</c>
	/// labeled alternative in <see cref="NetCalGParser.curveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtractionExpression([NotNull] NetCalGParser.SubtractionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>minimumExpression</c>
	/// labeled alternative in <see cref="NetCalGParser.curveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinimumExpression([NotNull] NetCalGParser.MinimumExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>maxPlusConvolutionExpression</c>
	/// labeled alternative in <see cref="NetCalGParser.curveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaxPlusConvolutionExpression([NotNull] NetCalGParser.MaxPlusConvolutionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>maximumExpression</c>
	/// labeled alternative in <see cref="NetCalGParser.curveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaximumExpression([NotNull] NetCalGParser.MaximumExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NetCalGParser.constantCurve"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantCurve([NotNull] NetCalGParser.ConstantCurveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NetCalGParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalOperator([NotNull] NetCalGParser.RelationalOperatorContext context);
}
