name: Nancy.Interactive-pack-release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "Nancy/Nancy.Interactive/Nancy.Interactive.csproj"
  pull_request:
    branches:
      - master
    paths:
      - "Nancy/Nancy.Interactive/Nancy.Interactive.csproj"

jobs:
  Nancy-Interactive-pack-release:
    runs-on: ubuntu-latest
        
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "Nancy/Nancy.sln"
      NANCY_INTERACTIVE: "Nancy/Nancy.Interactive/Nancy.Interactive.csproj"
      NANCY_INTERACTIVE_PACKS: "Nancy/Nancy.Interactive/bin/Release/**/*.nupkg"

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Build Nancy.Interactive
        run: dotnet build $NANCY_INTERACTIVE --configuration $BUILD_CONFIG

      # No actual tests available

      - name: Pack
        run: dotnet pack $NANCY_INTERACTIVE --configuration $BUILD_CONFIG --no-restore --no-build

      - name: Publish
        run: dotnet nuget push $NANCY_INTERACTIVE_PACKS --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
