name: Nancy-pack-release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: 
      - 'Nancy/Nancy/Nancy.csproj'
      - 'Nancy/Nancy/Nancy.LongRational.csproj'  
  pull_request:
    branches:
      - master
    paths: 
      - 'Nancy/Nancy/Nancy.csproj'
      - 'Nancy/Nancy/Nancy.LongRational.csproj'

jobs:
  Nancy-pack-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nancy-release: [ "", ".LongRational" ]
    
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "Nancy/Nancy.sln"
      NANCY: "Nancy/Nancy/Nancy${{ matrix.nancy-release }}.csproj"
      NANCY_TESTS: "Nancy/Nancy.Tests/Nancy.Tests${{ matrix.nancy-release }}.csproj"
      NANCY_PACKS: "Nancy/Nancy/bin/Release/**/*.nupkg"

    steps:
      - uses: actions/checkout@v6
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Build Nancy${{ matrix.nancy-release }}
        run: dotnet build $NANCY --configuration $BUILD_CONFIG

      - name: Build Nancy.Tests${{ matrix.nancy-release }}
        run: dotnet build $NANCY_TESTS --configuration $BUILD_CONFIG

      - name: Test Nancy${{ matrix.nancy-release }} on all target frameworks
        run: |
          dotnet test --project $NANCY_TESTS --configuration $BUILD_CONFIG --framework net8.0
          dotnet test --project $NANCY_TESTS --configuration $BUILD_CONFIG --framework net9.0
          dotnet test --project $NANCY_TESTS --configuration $BUILD_CONFIG --framework net10.0

      - name: Pack
        run: dotnet pack $NANCY --configuration $BUILD_CONFIG --no-restore

      - name: Publish
        run: dotnet nuget push $NANCY_PACKS --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
