name: Nancy.Expressions.Interactive-pack-release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "Nancy/Nancy.Expressions.Interactive/Nancy.Expressions.Interactive.csproj"
  pull_request:
    branches:
      - master
    paths:
      - "Nancy/Nancy.Expressions.Interactive/Nancy.Expressions.Interactive.csproj"

jobs:
  Nancy-Expressions-Interactive-pack-release:
    runs-on: ubuntu-latest
        
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "Nancy/Nancy.sln"
      NANCY_EXPRESSIONS_INTERACTIVE: "Nancy/Nancy.Expressions.Interactive/Nancy.Expressions.Interactive.csproj"
      NANCY_EXPRESSIONS_INTERACTIVE_PACKS: "Nancy/Nancy.Expressions.Interactive/bin/Release/**/*.nupkg"

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Build Nancy.Expressions.Interactive
        run: dotnet build $NANCY_EXPRESSIONS_INTERACTIVE --configuration $BUILD_CONFIG

      # No actual tests available

      - name: Pack
        run: dotnet pack $NANCY_EXPRESSIONS_INTERACTIVE --configuration $BUILD_CONFIG --no-restore --no-build

      - name: Publish
        run: dotnet nuget push $NANCY_EXPRESSIONS_INTERACTIVE_PACKS --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
